apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
spec:
  project: sample-app
  source:
    repoURL: https://github.com/faheem-khau9/devops-exercise-bundle.git
    targetRevision: HEAD
    path: helm/charts/kyverno-policies
    helm:
      releaseName: kyverno-policies
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      jqPathExpressions:
        - .spec.admission
        - .spec.rules[].skipBackgroundRequests
