apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: sample-app
  source:
    repoURL: https://github.com/faheem-khau9/devops-exercise-bundle.git
    targetRevision: HEAD
    path: helm/charts/sample-app
    helm:
      releaseName: sample-app
      valueFiles:
        - values.local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
